package uworkers.processor;

import java.io.IOException;
import java.io.Writer;

import javax.annotation.processing.Filer;
import javax.tools.JavaFileObject;

import com.github.mustachejava.DefaultMustacheFactory;
import com.github.mustachejava.Mustache;

public class ConsumerClassGenerator {

	final DefaultMustacheFactory mustacheFactory = new DefaultMustacheFactory();
	final Mustache providedClazzTemplate;
	final Filer filer;
	
	public ConsumerClassGenerator( String templateName, Filer filer ) {
		this.filer = filer;
		this.providedClazzTemplate = this.mustacheFactory.compile( templateName );
	}

	void generate( ConsumerClassData clazz ) throws IOException {
		String name = createClassCanonicalName( clazz );
		JavaFileObject sourceFile = filer.createSourceFile( name );
		Writer writer = sourceFile.openWriter();
		this.providedClazzTemplate.execute( writer, clazz );
		writer.close();
	}

	String createClassCanonicalName( ConsumerClassData clazz ) {
		return String.format( "%s.%sAutoGenerated%s%s",
				clazz.packageName,
				clazz.typeName,
				clazz.consumerName,
				clazz.consumerMethod );
	}
}
