package uworkers.core.endpoint;

public class EndpointAutoGeneratedProvideruworkersDotcoreDotendpointDotEndpointProducersproduceEndpoint implements trip.spi.ProviderFactory<uworkers.api.Endpoint> {

	@trip.spi.Provided trip.spi.ServiceProvider provider;

	public uworkers.api.Endpoint provide( trip.spi.ProviderContext context ) throws trip.spi.ServiceProviderException {
		try {
			final uworkers.core.endpoint.EndpointProducers factoryProvider = new uworkers.core.endpoint.EndpointProducers();
			provider.provideOn( factoryProvider );
			return factoryProvider.produceEndpoint( context );
		} catch( Throwable cause ) {
			throw new trip.spi.ServiceProviderException( cause );
		}
	}
}