package uworkers.core.endpoint;

public class SubscriberEndpointAutoGeneratedProvideruworkersDotcoreDotendpointDotEndpointProducersproduceSubscriberEndpoint implements trip.spi.ProviderFactory<uworkers.core.endpoint.SubscriberEndpoint> {

	@trip.spi.Provided trip.spi.ServiceProvider provider;

	public uworkers.core.endpoint.SubscriberEndpoint provide( trip.spi.ProviderContext context ) throws trip.spi.ServiceProviderException {
		try {
			final uworkers.core.endpoint.EndpointProducers factoryProvider = new uworkers.core.endpoint.EndpointProducers();
			provider.provideOn( factoryProvider );
			return factoryProvider.produceSubscriberEndpoint( context );
		} catch( Throwable cause ) {
			throw new trip.spi.ServiceProviderException( cause );
		}
	}
}